name: Update Subscription

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download subs
        run: |
          curl -L "https://raw.githubusercontent.com/qpginger/Mci/main/mci" -o sub1.txt
          curl -L "https://sub.firoozehmobile.sbs/sub/Zm94XzQ4Njc2NDksMTc4MTYxOTAzMwez2OQZEz0R" -o sub2.txt

      - name: Merge & clean vless links
        run: |
          cat sub1.txt sub2.txt | grep "vless://" | sort -u > mci

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add mci
          git commit -m "auto update sub" || exit 0
          git push
