name: Update Subscription

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download subscriptions
        run: |
          curl -L "https://raw.githubusercontent.com/qpginger/Mci/main/mci" -o old.txt
          curl -L "https://sub.firoozehmobile.sbs/sub/Zm94XzQ4Njc2NDksMTc4MTYxOTAzMwez2OQZEz0R" -o new.txt

      - name: Merge subscriptions
        run: |
          cat old.txt new.txt > mci

      - name: Commit update
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add mci
          git commit -m "Auto update subscription" || exit 0
          git push
